<%@ page import="model.User,model.Group,java.util.*" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%
  User loginedUser = (User) session.getAttribute("loginedUser");
  if (loginedUser == null) { response.sendRedirect("login.jsp"); return; }
  Group group = null;
  Object groupObj = request.getAttribute("group");
  if (groupObj instanceof Group) group = (Group) groupObj;
  String rawGroupId = request.getParameter("groupId");
  if (rawGroupId == null || rawGroupId.isBlank()) rawGroupId = request.getParameter("id");
  int groupId = -1;
  try { groupId = group != null ? group.getGroupId() : Integer.parseInt(rawGroupId); } catch(Exception e) { groupId = -1; }
  String groupName = group != null ? group.getGroupName() : "Dự án #" + (groupId > 0 ? groupId : "");
  int createdBy = group != null ? group.getCreatedBy() : -1;
  boolean isLeader = createdBy == loginedUser.getUserId();
%>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Zero-Sum Coin Exchange | Chi tiết nhóm</title><link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"/><link rel="stylesheet" href="assets/css/project-detail.css"/></head>
<body>
<script>
window.ZC_BACKEND_USER={id:"<%=loginedUser.getUserId()%>",fullName:"<%=loginedUser.getFullName()==null?"":loginedUser.getFullName().replace("\\","\\\\").replace("\"","\\\"")%>",email:"<%=loginedUser.getEmail()==null?"":loginedUser.getEmail().replace("\\","\\\\").replace("\"","\\\"")%>",username:"<%=loginedUser.getUsername()==null?"":loginedUser.getUsername().replace("\\","\\\\").replace("\"","\\\"")%>"};
window.ZC_BACKEND_GROUP={id:"<%=groupId%>",name:"<%=groupName.replace("\\","\\\\").replace("\"","\\\"")%>",createdBy:"<%=createdBy%>",isLeader:<%=isLeader%>};
localStorage.setItem("zc_logged_in","true");localStorage.setItem("zc_user_id",window.ZC_BACKEND_USER.id);localStorage.setItem("zc_user_name",window.ZC_BACKEND_USER.fullName||window.ZC_BACKEND_USER.username||"Team Member");localStorage.setItem("zc_current_project_id",window.ZC_BACKEND_GROUP.id);
</script>
<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-icon">ZC</div><div class="brand-text"><h2>Zero-Sum</h2><p>Coin Exchange</p></div></div><nav class="menu"><a class="menu-item" href="MyGroupsServlet">Trang chủ</a><button class="menu-item project-menu-toggle active" id="projectMenuToggle" type="button">Dự án</button><div class="project-submenu" id="sidebarProjectList"></div><a class="menu-item" href="notifications.jsp">Thông báo</a><a class="menu-item" href="account.jsp">Tài khoản</a><a class="menu-item" href="faq.jsp">FQA</a><button class="menu-item logout-btn" id="logoutBtn" type="button">Đăng xuất</button></nav><div class="sidebar-card"><span>Current project</span><strong id="sidebarProjectCode">#<%=groupId%></strong><p id="roleNote">Group ID: <%=groupId%></p></div></aside>
<main class="main-content" id="detail"><header class="topbar"><div><p class="eyebrow">Chi tiết dự án</p><h1 id="projectName"><%=groupName%></h1><p class="page-desc" id="projectDesc">Group ID: <strong id="groupIdText"><%=groupId%></strong> <button class="secondary-btn" id="copyGroupIdBtn" type="button" style="padding:8px 10px;margin-left:8px">Copy Group ID</button></p></div><div class="account-box"><span>Xin chào</span><strong id="currentUserName"><%=loginedUser.getFullName()!=null?loginedUser.getFullName():loginedUser.getUsername()%></strong><em id="currentUserRole"><%=isLeader?"Bạn là nhóm trưởng":"Bạn là thành viên"%></em></div></header>
<section class="project-summary"><article><span>Group ID</span><strong id="marketIndex"><%=groupId%></strong><p id="marketChange" class="up">Mã tham gia</p></article><article><span>Thành viên</span><strong id="memberCount">--</strong><p>Do backend cung cấp</p></article><article><span>Tổng task</span><strong id="taskCount">--</strong><p>Đang theo dõi</p></article><article><span>Quyền</span><strong id="deadlineText"><%=isLeader?"Leader":"Member"%></strong><p>Vai trò hiện tại</p></article></section>
<% if (isLeader) { %><section class="panel" id="leaderActions" style="margin-bottom:20px"><div class="panel-header"><div><h2>Quản lý thành viên</h2><p>Nhóm trưởng có thể duyệt yêu cầu tham gia và kick thành viên nếu backend có servlet tương ứng.</p></div></div><div class="section-box"><h3 style="margin-bottom:12px">Duyệt thành viên</h3><form action="ApproveMemberServlet" method="post" class="form-grid"><input type="hidden" name="groupId" value="<%=groupId%>"><input name="username" type="text" placeholder="Username cần duyệt" required><button class="primary-btn" type="submit">Duyệt vào nhóm</button></form></div><div class="section-box"><h3 style="margin-bottom:12px">Kick thành viên</h3><form action="KickMemberServlet" method="post" class="form-grid"><input type="hidden" name="groupId" value="<%=groupId%>"><input name="username" type="text" placeholder="Username cần kick" required><button class="ghost-btn" type="submit">Kick khỏi nhóm</button></form></div></section><% } %>
<section class="panel chart-panel"><div class="panel-header"><div><h2>Dashboard tiến độ coin</h2><p>Phần coin/task sẽ hiển thị khi backend cung cấp dữ liệu hoặc khi dùng bản localStorage preview.</p></div><button class="secondary-btn" id="simulateMarketBtn" type="button">Cập nhật tiến độ</button></div><div class="chart-wrap"><canvas id="coinChart" width="1200" height="460"></canvas></div><div class="legend" id="chartLegend"></div></section><section class="panel board-panel"><div class="panel-header small"><div><h2>Bảng coin thành viên</h2><p>Tổng quan giá trị coin và thay đổi phiên gần nhất.</p></div></div><div class="market-board-grid" id="marketBoard"></div></section><section class="panel" id="members"><div class="panel-header"><div><h2>Thành viên & bài làm</h2><p>Thành viên cập nhật bài của mình; mọi người đều xem và đánh giá bài làm của nhau.</p></div></div><div class="member-grid" id="memberGrid"></div></section></main></div>
<div class="modal" id="taskModal" aria-hidden="true"><div class="modal-content large-modal"><button class="close-btn" id="closeTaskModal" type="button">×</button><div class="modal-title"><span class="tag">Task Detail</span><h2 id="modalMemberName">Chi tiết thành viên</h2><p id="modalMemberMeta">Xem chi tiết bài làm và đánh giá đóng góp.</p></div><div class="score-note"><strong>Thang đánh giá:</strong><span>1⭐ Tệ, cần làm lại</span><span>2⭐ Cần chỉnh sửa</span><span>3⭐ Đạt yêu cầu</span><span>4⭐ Tốt</span><span>5⭐ Xuất sắc</span></div><div class="table-wrap"><table><thead><tr><th>Task</th><th>Deadline</th><th>Trạng thái</th><th>Bài làm / cập nhật</th><th>Đánh giá</th></tr></thead><tbody id="modalTaskBody"></tbody></table></div><div class="modal-actions"><button class="primary-btn" id="saveTaskUpdates" type="button">Lưu cập nhật</button></div></div></div>
<script src="assets/js/project-detail.js"></script></body></html>
